name: Node.js CI
permissions:
    contents: read

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            APP_ENV: test
            NODE_ENV: test

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm i
            - run: npm run build
            - run: npm run lint

            - name: Run Tests with Coverage
              run: npm run cover
